---
- name: pf.conf deployed
  template:
    src: pf.conf
    dest: /etc/
    owner: root
    group: wheel
    mode: 0600
    backup: no

- name: pf.rules deployed
  template:
    src: pf.rules
    dest: /etc/pf.anchors/
    owner: root
    group: wheel
    mode: 0600
    backup: no
  notify:
    - restart pf

- name: martians updated
  lineinfile:
    path: /etc/pf/martians
    line: "!{{ wireguard_subnet }}"

- name: anchor reloaded
  shell: "/sbin/pfctl -a pf.rules -F Tables && /sbin/pfctl -a pf.rules -f /etc/pf.anchors/pf.rules"
  changed_when: false
  check_mode: no
